######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 11 00:18:52 2013
######################################################################

TEMPLATE = app
TARGET = unqlite-qt
DEPENDPATH += .
INCLUDEPATH += .

include(unqlite-qt.pri)

CONFIG += qt debug

SOURCES +=  main.cpp 

